fix(checkout): PI-48 Place Order button is disabled when customer wit…
bigcommerce/checkout-js pull request #1279
Opened 2023-05-17 07:57 UTC by bc-ania

…h stored credit card deletes and re-adds card

## What?
Place Order button on checkout is disabled when a customer with a stored credit card deletes, and re-adds card on checkout. The issue also occurs if simply deleting the stored card, and trying to use a different card with Adyen(non-stored).

@bigcommerce/checkout

2023-05-17 08:15 UTC, vitalii-koshovyi requested changes
Could you please check it with AdyenV3 as well. I believe it has the same problem.

2023-05-17 14:17 UTC, vitalii-koshovyi commented
Please add some screenshots or video that will show changes .

2023-05-18 05:12 UTC, bc-peng approved these changes
LGTM 👍

2023-05-18 06:02 UTC, animesh1987 commented
Hey @bc-ania can you please adjust the PR description before merging. Thanks.

2023-05-19 08:54 UTC, merged