feat(payment): PAYPAL-2620 paypal-express-integration package
bigcommerce/checkout-js pull request #1605
Opened 2023-11-30 11:34 UTC by bc-nick

## What?

Created `paypal-express-integration` package

## Why?

To separate and move related code

@bigcommerce/team-checkout

2023-11-30 12:06 UTC, serhii-tkachenko approved these changes

2023-12-01 01:57 UTC, bc-peng commented on packages/paypal-express-integration/src/index.ts
Can you please explain why are you making this skeleton package here?
Would it be possible to create a PR with actual content in it?

2023-12-06 22:09 UTC, bc-peng commented on packages/paypal-express-integration/project.json
> +        "lintFilePatterns": ["packages/paypal-express-integration/**/*.ts"]
```suggestion
        "lintFilePatterns": ["packages/paypal-express-integration/**/*.{ts,tsx}"]
```

2023-12-07 00:13 UTC, bc-peng commented
Can we add an e2e test to the package?

2023-12-07 08:25 UTC, bc-nick commented on packages/paypal-express-integration/project.json
> +        "lintFilePatterns": ["packages/paypal-express-integration/**/*.ts"]
done

2023-12-07 08:47 UTC, bc-nick commented
> Can we add an e2e test to the package?

@bc-peng would be better to create another ticket for writing e2e test and do it separately. Because i already have combined a two tickets to one PR.
I will create a ticket for this and take it to work in one of the next sprints

2023-12-07 15:31 UTC, serhii-tkachenko approved these changes

2023-12-07 15:31 UTC, serhii-tkachenko commented on .github/CODEOWNERS
> +/packages/paypal-express-integration @bigcommerce/team-integrations
```suggestion
/packages/paypal-express-integration @bigcommerce/team-paypal 
```

2023-12-07 22:52 UTC, bc-peng approved these changes
LGTM. 👏👏

2023-12-08 09:42 UTC, vitalii-koshovyi requested changes
We need to make this package generic. This functionality should be used by other providers. For example https://github.com/bigcommerce/checkout-js/blob/master/packages/bluesnap-direct-integration/src/BlueSnapDirectAlternativePaymentMethod.tsx
 potentially it could be used by a lot of providers from the `core`

I believe we need to add e2e tests, to be sure that refactoring doesn't break anything.

My proposition is:

**1) Make this package generic for other providers**
You need to create module resolver here https://github.com/bigcommerce/checkout-js/tree/master/packages/hosted-payment-integration/src instead of creation separate module for pp-express
**We just need to figure out what to do with provider specific initialization props** 
I mean this one 
```
paypalexpress: {
     useRedirectFlow: true,
},
```
**2) Create separate package paypal-express-integration** that will contain e2e tests

**3) Remove Bluesnap** [file](https://github.com/bigcommerce/checkout-js/blob/master/packages/bluesnap-direct-integration/src/BlueSnapDirectAlternativePaymentMethod.tsx) and add bluesnap resolver [{ gateway: 'bluesnapdirect' }] to the hosted-payment-integration toResolvableComponent function call.

cc @serhii-tkachenko @PavlenkoM

2023-12-08 09:49 UTC, vitalii-koshovyi commented
@bc-peng @animesh1987 @serhii-tkachenko @bc-nick @PavlenkoM  do you agree with my idea that https://github.com/bigcommerce/checkout-js/tree/master/packages/hosted-payment-integration/src should have its own resolver? I think it should be generic for other providers as well. To avoid code duplication.
But we should have a provider specific package that will have e2e tests.
You can check my comment above

2023-12-08 09:57 UTC, serhii-tkachenko commented
> @bc-peng @animesh1987 @serhii-tkachenko @bc-nick @PavlenkoM do you agree with my idea that https://github.com/bigcommerce/checkout-js/tree/master/packages/hosted-payment-integration/src should have its own resolver? I think it should be generic for other providers as well. To avoid code duplication. But we should have a provider specific package that will have e2e tests. You can check my comment above

Yes, I agree with the idea, that we probably should reduce amount of code (packages). We can make the same as we have in CheckoutButton - generic component for buttons on checkout page.

2023-12-08 14:26 UTC, vitalii-koshovyi approved these changes
After discussion with @serhii-tkachenko and @bc-nick we decided to leave it as it is.
Because providers have unique initializationData and we didn't find a way to make it generic for all providers. 
Current approach is a simplest from other variants that we discussed. 

I would recommend to add e2e test for this paypal-express package.

Well done!

2023-12-18 10:02 UTC, merged