[WIP] fix(payments): INT-3140 Enable checkout button with googlepay when use store credit - StripeV3
bigcommerce/checkout-js pull request #412
Opened 2020-09-15 16:59 UTC by BC-AOrtiz

[INT-3140](https://jira.bigcommerce.com/browse/INT-3140)

## What?
- Validate if shopper use store credit to enable the checkout button whit wallet

## Why?
- Shopper can place a order when use store credit and googlepay is enabled.

## Testing / Proof
Unit test

@bigcommerce/checkout

2020-09-18 22:39 UTC, mauricio-sg requested changes
I have a doubt and a couple of suggestions you could try. Let me know if you have any questions.

2020-09-18 22:39 UTC, mauricio-sg commented on src/app/payment/paymentMethod/WalletButtonPaymentMethod.tsx
> +        if (normalizeWalletPaymentData(method.initializationData) || this.isStoreCreditUsed()) {
I think this calc is already in the state `checkoutState.data.isPaymentDataRequired`.
```suggestion
        if (normalizeWalletPaymentData(method.initializationData) || !isPaymentDataRequired) {
```

2020-09-18 22:39 UTC, mauricio-sg commented on src/app/payment/paymentMethod/WalletButtonPaymentMethod.tsx
> +    const { data: { getBillingAddress, getCheckout, getCustomer } } = checkoutState;
I think this is all you need:
```suggestion
    const { data: { getBillingAddress, getCheckout, isPaymentDataRequired } } = checkoutState;
```

2020-09-18 22:39 UTC, mauricio-sg commented on src/app/payment/paymentMethod/WalletButtonPaymentMethod.tsx
> +        storeCreditAmount,
```suggestion
        isPaymentDataRequired
```

2020-09-21 14:12 UTC, BC-AOrtiz commented on src/app/payment/Payment.tsx
> +            await this.componentDidMount();
I need to reload the payments to run again the validation to enable or disable the place order button when you click on use store credit checkbox

2020-09-21 14:38 UTC, BC-AOrtiz commented
♻️ @mauricio-sg changes have been addressed, plase take another look

2020-09-21 16:58 UTC, ValeriaRivas commented
💚  Tested

2020-09-21 17:45 UTC, mauricio-sg requested changes
Just a few more adjustments.

2020-09-21 17:45 UTC, mauricio-sg commented on src/app/payment/Payment.tsx
> +            await this.componentDidMount();
So `componentDidUpdate` is the right place to check that, it also calls `toggleSubmit` method like `componentDidMount` does but this time validates if something changed, in this case you could check if `isPaymentDataRequired !== prevIsPaymentDataRequired` to determine if `toggleSubmit` should be called.

2020-09-21 17:45 UTC, mauricio-sg commented on src/app/payment/paymentMethod/WalletButtonPaymentMethod.tsx
> +    isPaymentDataRequired: boolean;
We try to keep props sorted, `isPaymentDataRequired` goes between `expiryYear` and `isPaymentSelected` sorry, my mistake, I didn't mention it before. 🙏

2020-09-21 17:45 UTC, mauricio-sg commented on src/app/payment/paymentMethod/WalletButtonPaymentMethod.tsx
> +        isPaymentDataRequired: isPaymentDataRequired(),
Same here, `isPaymentDataRequired` goes after `cardName` 🙈

2020-09-21 19:18 UTC, BC-AOrtiz commented
♻️ @mauricio-sg changes have been addressed, plase take another look

2020-09-21 20:46 UTC, mauricio-sg requested changes
These are the last changes, I promise 😬

2020-09-21 20:46 UTC, mauricio-sg commented on src/app/payment/paymentMethod/WalletButtonPaymentMethod.spec.tsx
> +        mount(<WalletButtonPaymentMethodTest { ...props } />);
Just add the following code on line 50 and these changes won't be necessary.
```
        jest.spyOn(checkoutState.data, 'isPaymentDataRequired')
            .mockReturnValue(true);
```

2020-09-21 20:46 UTC, mauricio-sg commented on src/app/payment/paymentMethod/WalletButtonPaymentMethod.spec.tsx
> +    it('enable submit button with store credit', () => {
🍹
```suggestion
    it('enables submit button if payment data is not required', () => {
```

2020-09-21 20:46 UTC, mauricio-sg commented on src/app/payment/paymentMethod/WalletButtonPaymentMethod.spec.tsx
> +        />);
```suggestion
        jest.spyOn(checkoutState.data, 'isPaymentDataRequired')
            .mockReturnValue(false);

        mount(<WalletButtonPaymentMethodTest { ...defaultProps } />);
```

2020-09-21 21:52 UTC, BC-AOrtiz commented
♻️ @mauricio-sg changes have been addressed, plase take another look

2020-09-21 22:16 UTC, mauricio-sg approved these changes
Thank you @BC-AOrtiz, LGTM 👍

2020-09-21 22:16 UTC, mauricio-sg commented on src/app/payment/paymentMethod/WalletButtonPaymentMethod.spec.tsx
> +        />);
🍹 
```suggestion
        mount(<WalletButtonPaymentMethodTest { ...defaultProps } />);
```

2020-09-24 00:46 UTC, capsula4 approved these changes

2020-09-24 23:09 UTC, merged