feat(payment): INT-3946 added locale from browser on masterpass SRC
bigcommerce/checkout-js pull request #623
Opened 2021-06-30 23:52 UTC by BC-AxelMalagon

## What? [INT-3946](https://jira.bigcommerce.com/browse/INT-3946)
Added locale from browser on masterpass SRC.

## Why?
In order to be able to see masterpass or SRC button based on shopper locale.

## Testing / Proof
Unit test

@bigcommerce/checkout

2021-07-01 01:30 UTC, vmparra approved these changes
LGTM 👍🏻

2021-07-01 02:30 UTC, icatalina commented on src/app/payment/paymentMethod/MasterpassPaymentMethod.tsx
> +    const locale = getLocale(localeLanguage);
The current language in checkout might not match the one from the browser. Would it be better to honour the one set for the rest of storefront in this case?

2021-07-02 21:42 UTC, BC-AxelMalagon commented
@icatalina could you give another check please? ♻️

2021-07-05 00:53 UTC, icatalina requested changes
Are we missing tests for these changes?

2021-07-05 00:53 UTC, icatalina commented on src/app/payment/paymentMethod/MasterpassPaymentMethod.tsx
> +    }, []);
This method is react agnostic and uses nothing from the component scope. Could we move it outside the component?

2021-07-05 00:53 UTC, icatalina commented on src/app/payment/paymentMethod/MasterpassPaymentMethod.tsx
> +        const auxLocale = localeLanguage.replace(/[-_]/g, '_');
Why are we replacing `_` with `_`?

```suggestion
        const auxLocale = localeLanguage.replace(/[-]/g, '_');
```

2021-07-05 00:53 UTC, icatalina commented on src/app/payment/paymentMethod/MasterpassPaymentMethod.tsx
> +        const formatedLocale = auxLocale.includes('_') ? `${auxLocale}` : `${auxLocale}_${auxLocale}`;
There's no need to wrap the first part of the ternary in a string literal, `auxLocale` is already a string.

```suggestion
        const formatedLocale = auxLocale.includes('_') ? auxLocale : `${auxLocale}_${auxLocale}`;
```

2021-07-05 00:58 UTC, icatalina commented
Also, after looking at the documentation, it seems like `en_en` is not a valid locale:

https://developer.mastercard.com/masterpass/documentation/migration/masterpass_to_src_migration/#update-merchant-js-library

Do we want to be more specific about some of these?

2021-07-13 03:29 UTC, vmparra commented
Closing as @BC-AxelMalagon no longer works for BC

2021-07-13 03:29 UTC, closed without merging