feat(payment): INT-4897 Humm - Show Humm as payment method
bigcommerce/checkout-js pull request #722
Opened 2021-10-08 19:45 UTC by roberbnd

## What? [INT-4897](https://jira.bigcommerce.com/browse/INT-4897)
Adding humm as payment method, specifying the logo, humm is a external payment method then we going to redirect the pay.

## Why?
it's need it to support it when we want to pay.

## Testing / Proof
![image](https://user-images.githubusercontent.com/4907027/140761022-5dfac835-fa74-4d8a-819e-1b555163d20c.png)

@bigcommerce/checkout

2021-11-04 14:03 UTC, josesonora approved these changes

2021-11-04 14:03 UTC, josesonora commented on src/app/payment/Payment.tsx
> +        // `checkout.com`, `converge`, `sagepay`, `stripev3`, `humm` and `sezzle`. They require
this is not necessary

2021-11-04 14:10 UTC, josesonora requested changes
I realized that the logo shown in your proof is not the same as the one that is specified in the ticket https://jira.bigcommerce.com/browse/INT-4006, if it was changed to the correct one please update the proof.

Please also be more descriptive when writing the **What & Why** sections

2021-11-08 15:37 UTC, josesonora approved these changes

2021-11-10 23:35 UTC, leeBigCommerce approved these changes
👍

2021-11-10 23:36 UTC, leeBigCommerce commented
@bigcommerce/checkout Code owner review please

2021-11-26 00:34 UTC, animesh1987 approved these changes

2021-12-03 00:24 UTC, merged