test(payment): INT-4855 increase code coverage on CheckoutcomCustomFo…
bigcommerce/checkout-js pull request #738
Opened 2021-10-29 19:57 UTC by JoseAlvarezHdz

## What?  [INT-4855](https://jira.bigcommerce.com/browse/INT-4855)

Increase CheckoutcomCustomFormFields code coverage

## Why?
To increase code coverage

## Testing / Proof
### Before

![Screen Shot 2021-10-29 at 14 56 50](https://user-images.githubusercontent.com/69221626/139494538-f9a2e46a-2f38-426c-9a05-0bc9c52b969e.png)
 
### Now

![Screen Shot 2021-10-29 at 14 53 58](https://user-images.githubusercontent.com/69221626/139494234-5a0a76f7-a0b5-4174-932b-48547714c8fe.png)

@bigcommerce/checkout. @bigcommerce/apex-integrations

2021-10-29 20:12 UTC, JoseAlvarezHdz commented
![Screen Shot 2021-10-29 at 14 57 55](https://user-images.githubusercontent.com/69221626/139494654-65df822c-fe15-4e20-8ecd-caa1f0691ca9.png)

The only things left to test are 

1. `optional chaining` which i cant test because cant undefined them
2. not defined `_selectedIssuer` but it wont happened as `handleClick` is only trigger when you click on an option so that find will never return an empty object but `find` returns  `T | undefined` so thats why its left

2021-10-29 20:30 UTC, vmparra requested changes
Hi @JoseAlvarezHdz, this is great, thank you for doing it. I left a few comments, please let me know if you have questions.

2021-10-29 20:30 UTC, vmparra commented on src/app/payment/paymentMethod/CheckoutcomCustomFormFields.spec.tsx
> +        it('should call handleclick on DropdownTrigger change', () => {
Can we please add a description of what  is happening on the UI (i.e. Shopper selects a payment method from dropdown, etc.)

2021-10-29 20:30 UTC, vmparra commented on src/app/payment/paymentMethod/CheckoutcomCustomFormFields.spec.tsx
> +        it('should render the Fawry fieldset', () => {
Same as above

2021-10-29 20:50 UTC, FranciscoOnt approved these changes
Just a small typo 👍

2021-10-29 20:50 UTC, FranciscoOnt commented on src/app/payment/paymentMethod/CheckoutcomCustomFormFields.spec.tsx
> +            if: 'fawry',
shouldn't this be `id`?

2021-10-29 21:26 UTC, JoseAlvarezHdz commented on src/app/payment/paymentMethod/CheckoutcomCustomFormFields.spec.tsx
> +            if: 'fawry',
Done!

2021-10-29 21:50 UTC, vmparra approved these changes
LGTM 👍🏻

2021-10-31 23:52 UTC, leeBigCommerce approved these changes
LGTM 👍

2021-10-31 23:53 UTC, leeBigCommerce commented
@bigcommerce/checkout code owner review please ✨

2021-11-26 00:36 UTC, animesh1987 approved these changes

2021-12-16 04:01 UTC, merged