fix(payment) INT-6328 Bluesnap open a new tab insted of using iframe …
bigcommerce/checkout-js pull request #988
Opened 2022-08-22 23:13 UTC by BC-luna

…to complete order

## What?
...

## Why?
...

## Testing / Proof
...

@bigcommerce/checkout

2022-08-23 14:29 UTC, vmparra approved these changes
LGTM 👍🏻

2022-08-23 16:50 UTC, FranciscoOnt requested changes
Just Some small changes

2022-08-23 17:20 UTC, BC-luna commented on packages/core/src/app/payment/paymentMethod/BlueSnapV2PaymentMethod.tsx
> +                <LoadingOverlay isLoading={ !!isLoadingIframe } unmountContentWhenLoading={ !!paymentPageContent }  />
@FranciscoOnt comments addressed, could you pls take another look?

2022-08-23 17:45 UTC, FranciscoOnt approved these changes

2022-08-25 00:14 UTC, animesh1987 approved these changes

2022-09-05 04:49 UTC, merged